name: TruLove
favicon: null
layout_spectrum: 0.9762905084062368
typography_spectrum: 0.5349839988630265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4e1118'
    - '#006738'
    - '#c3aeb2'
    - '#70474d'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
